# Generated by Django 5.2.17 on 2026-09-16 23:44

import login_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', login_app.models.UsuarioManager()),
            ],
        ),
    ]
