import django.contrib.auth.models
import django.utils.timezone
import login_app.models
from django.db import migrations, models


def require_empty_users(apps, schema_editor):
    usuario = apps.get_model('login_app', 'Usuario')
    if usuario.objects.exists():
        raise RuntimeError(
            'La migración a cédula requiere una carga manual de cédulas '
            'para los usuarios existentes antes de continuar.'
        )


CREATE_SCHEMA = '''
ALTER TABLE "django_admin_log"
    ALTER COLUMN "user_id" TYPE varchar(20)
    USING "user_id"::text;
CREATE TABLE "login_app_usuario" (
    "cedula" varchar(20) NOT NULL PRIMARY KEY,
    "password" varchar(128) NOT NULL,
    "last_login" timestamp with time zone NULL,
    "is_superuser" boolean NOT NULL,
    "first_name" varchar(150) NOT NULL,
    "last_name" varchar(150) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL,
    "rol" varchar(20) NOT NULL
);
CREATE TABLE "login_app_usuario_groups" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" varchar(20) NOT NULL,
    "group_id" integer NOT NULL
);
CREATE TABLE "login_app_usuario_user_permissions" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" varchar(20) NOT NULL,
    "permission_id" integer NOT NULL
);
ALTER TABLE "login_app_usuario_groups"
    ADD CONSTRAINT "login_app_usuario_groups_usuario_id_group_id_5f45e1d9_uniq"
    UNIQUE ("usuario_id", "group_id");
ALTER TABLE "login_app_usuario_groups"
    ADD CONSTRAINT "login_app_usuario_gr_usuario_id_a69bae77_fk_login_app"
    FOREIGN KEY ("usuario_id") REFERENCES "login_app_usuario" ("cedula")
    DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "login_app_usuario_groups"
    ADD CONSTRAINT "login_app_usuario_groups_group_id_f1c003c2_fk_auth_group_id"
    FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id")
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "login_app_usuario_groups_usuario_id_a69bae77"
    ON "login_app_usuario_groups" ("usuario_id");
CREATE INDEX "login_app_usuario_groups_group_id_f1c003c2"
    ON "login_app_usuario_groups" ("group_id");
ALTER TABLE "login_app_usuario_user_permissions"
    ADD CONSTRAINT "login_app_usuario_user_p_usuario_id_permission_id_a04101b2_uniq"
    UNIQUE ("usuario_id", "permission_id");
ALTER TABLE "login_app_usuario_user_permissions"
    ADD CONSTRAINT "login_app_usuario_us_usuario_id_50c3a0bd_fk_login_app"
    FOREIGN KEY ("usuario_id") REFERENCES "login_app_usuario" ("cedula")
    DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "login_app_usuario_user_permissions"
    ADD CONSTRAINT "login_app_usuario_us_permission_id_d0b97b67_fk_auth_perm"
    FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id")
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "login_app_usuario_user_permissions_usuario_id_50c3a0bd"
    ON "login_app_usuario_user_permissions" ("usuario_id");
CREATE INDEX "login_app_usuario_user_permissions_permission_id_d0b97b67"
    ON "login_app_usuario_user_permissions" ("permission_id");
ALTER TABLE "django_admin_log"
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_login_app_usuario_id"
    FOREIGN KEY ("user_id") REFERENCES "login_app_usuario" ("cedula")
    DEFERRABLE INITIALLY DEFERRED;
'''

DROP_SCHEMA = '''
ALTER TABLE "django_admin_log"
    DROP CONSTRAINT IF EXISTS "django_admin_log_user_id_c564eba6_fk_login_app_usuario_id";
DROP TABLE IF EXISTS "login_app_usuario_groups";
DROP TABLE IF EXISTS "login_app_usuario_user_permissions";
DROP TABLE IF EXISTS "login_app_usuario";
'''

MIGRATE_SCHEMA = DROP_SCHEMA + CREATE_SCHEMA


class Migration(migrations.Migration):
    dependencies = [
        ('login_app', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.RunPython(require_empty_users, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(MIGRATE_SCHEMA, migrations.RunSQL.noop),
            ],
            state_operations=[
                migrations.DeleteModel(name='Usuario'),
                migrations.CreateModel(
                    name='Usuario',
                    fields=[
                        ('cedula', models.CharField(
                            help_text='Identificador único del usuario, sin puntos ni guiones.',
                            max_length=20,
                            primary_key=True,
                            serialize=False,
                            verbose_name='cédula de identidad',
                        )),
                        ('password', models.CharField(max_length=128, verbose_name='password')),
                        ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                        ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                        ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                        ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                        ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                        ('is_active', models.BooleanField(default=True, help_text='Unselect this instead of deleting accounts.', verbose_name='active')),
                        ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                        ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('DOCENTE', 'Docente'), ('PADRE_TUTOR', 'Padre/Tutor')], max_length=20)),
                        ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                        ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                    ],
                    options={
                        'verbose_name': 'user',
                        'verbose_name_plural': 'users',
                    },
                    managers=[
                        ('objects', login_app.models.UsuarioManager()),
                    ],
                ),
            ],
        ),
    ]
